### ISSUE TITLE
I fucking don't 

### ISSUE THREAD

**Issue by ghost** [endlessalpacaYT/XPanel#5]
Stop editing this you child!

**Comment by optixyt0** [comment]
lets see you make smth better @MarvelcoOGFN

**Comment by optixyt0** [comment]
without skidding it fully. not one bit of skidded code

**Comment by ghost** [comment]
> without skidding it fully. not one bit of skidded code

Stop acting like a child and grow up

**Comment by PongooDev** [comment]
> > without skidding it fully. not one bit of skidded code
> 
> Litterly the stuff I do and modify is 100% percent skidded

Bro you ARE the biggest skid, forget akadi and everyone else, you litterally skidded lawinv2 in the first place

**Comment by ghost** [comment]
> > > without skidding it fully. not one bit of skidded code
> > 
> > 
> > Litterly the stuff I do and modify is 100% percent skidded
> 
> Bro you ARE the biggest skid, forget akadi and everyone else, you litterally skidded lawinv2 in the first place

.

**Comment by ghost** [comment]
> > without skidding it fully. not one bit of skidded code
> 
> I love to skid code!
> 

Stop fucking editing my messages

**Comment by PongooDev** [comment]
> > > without skidding it fully. not one bit of skidded code
> > 
> > 
> > I love to skid code!
> 
> Stop fucking editing my messages

nah, id rather not till you leave me alone my friend

**Comment by ghost** [comment]
> > > > without skidding it fully. not one bit of skidded code
> > > 
> > > 
> > > I love to skid code!
> > 
> > Stop fucking editing my messages
> 
> nah, id rather not till you leave me alone my friend

I did bro I didn't contact you today so stop acting like a child

**Comment by ghost** [comment]
@endlessalpacaYT @optixyt0 I don't want nothing to do with you nor I ever want to speak to you again so leave me alone and ill leave you alone unless you are going to keep being a child

**Comment by PongooDev** [comment]
> @endlessalpacaYT @optixyt0 I don't want nothing to do with you nor I ever want to speak to you again so leave me alone and ill leave you alone unless you are going to keep being a child

alright then, deal

**Comment by optixyt0** [comment]
deal
